WIP - Try to use absolute path when loading downloaded external storage file into RNTP
Stuck on this error:

Exception in native call
                                                                                                    java.lang.SecurityException: Permission Denial: reading com.android.externalstorage.ExternalStorageProvider uri content://com.android.externalstorage.documents/tree/primary/Podcasts/document/primary/Podcasts/GlSXmyuhF.mp3 from pid=25029, uid=10344 requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs