Try to fix t.onPress crash
#1703

com.facebook.react.modules.core.ExceptionsManagerModule.reportException
ExceptionsManagerModule.java, line 83
com.facebook.react.common.JavascriptException: TypeError: t.onPress is not a function. (In 't.onPress()', 't.onPress' is null)